config/routes.rb
Rails.application.routes.draw do
  resources :beverages
  resources :motors
  get "/beverages/status/:id", to: "beverages#status"
  post "/beverages/dispense", to: "beverages#dispense"
  post "/motors/find", to: "motors#find"
  post "/motors/flush", to: "motors#flush"
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  has_one :motor
end

app/controllers/beverages_controller.rb
require "open-uri"
require "base64"

class BeveragesController < ApplicationController
  before_action :set_beverage, only: %i[ show edit update destroy ]
  protect_from_forgery unless: -> { request.format.json? }

  # GET /beverages or /beverages.json
  def index
    @beverages = Beverage.all.to_a
    respond_to do |format|
      format.html { STDERR.puts "INDEX...."; render :index }
      format.json { STDERR.puts "JSON...."; render json: @beverages }
    end
  end

  # GET /beverages/1 or /beverages/1.json
  def show
  end

  # GET /beverages/new
  def new
    @beverage = Beverage.new
  end

  # GET /beverages/1/edit
  def edit
  end

  # POST /beverages or /beverages.json
  def create
    @beverage = Beverage.new(beverage_params)
    data = snarf_image_data

    respond_to do |format|
      if @beverage.save
        if data
          STDERR.puts "UPDATING DATA"
          @beverage.image_data = Base64.encode64(data)
          @beverage.save
        end
        if mid = motor_id_param
          new_motor = Motor.find(mid)
          pp new_motor.id
          pp new_motor.uuid
          @beverage.motor = new_motor if new_motor
          @beverage.save
        end
        format.html { redirect_to @beverage, notice: "Beverage was successfully created." }
        format.json { render :show, status: :created, location: @beverage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beverages/1 or /beverages/1.json
  def update
    respond_to do |format|
      data = snarf_image_data
      if @beverage.update(beverage_params)
        if data
          STDERR.puts "UPDATING DATA"
          @beverage.image_data = Base64.encode64(data)
          @beverage.save
        end
        if mid = motor_id_param
          new_motor = Motor.find(mid)
          pp new_motor.id
          pp new_motor.uuid
          @beverage.motor = new_motor if new_motor
          @beverage.save
        end

        format.html { redirect_to @beverage, notice: "Beverage was successfully updated." }
        format.json { render :show, status: :ok, location: @beverage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  def snarf_image_data
    data = nil
    STDERR.puts "snarfing us up some image data from #{beverage_params.inspect}"
    begin
      data = nil
      URI.open(beverage_params[:image_url]) do |f|
        data = f.read
      end
    rescue Exception => e
      STDERR.puts e
      # The right thing to do here would be to report an error.
      # So maybe do that?
    end
    
    data
  end

  # DELETE /beverages/1 or /beverages/1.json
  def destroy
    @beverage.destroy
    respond_to do |format|
      format.html { redirect_to beverages_url, notice: "Beverage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /beverages/dispense
  #   ids: list of IDs.
  def dispense
    STDERR.puts "dispensing for #{params[:ids]}"
    
    CurrentDrink[:beverage_ids] = params[:ids]
    CurrentDrink[:token] = Random.uuid
    amounts_dispensed = []

    STDERR.puts params.inspect
    params[:ids].each do |id|
      beverage = Beverage.find_by(identifier: id)
      if beverage
        STDERR.puts beverage.inspect
        STDERR.puts "sending D,#{beverage.amount} to #{motor.uuid}"

        Publisher.publish({
          "name" => motor.uuid,
          "command" => "D,#{beverage.amount}"
        }.to_json)

        amounts_dispensed << {motor: motor, amount: beverage.amount}
        # This is substandard. It is just waiting until it gets any message back from the bot
        # in response to a check on the amount dispensed. At the same time, the time to dispense 10-30ml
        # should be about 1 to 2.5 seconds, so do we really need to be paranoid beyond the time
        # it takes to confirm that _something_ has happened with each motor involved?
        # Probably, yes, but it is also 5:00 am, so live by the MVP, die by the MVP.
        # TODO: Make this smarter and less bad later.
        while amounts_dispensed.any?
          Publisher.publish({
            "name" => amounts_dispensed.last[:motor].uuid,
            "command" => "R"
          })
          while !(response = DrinkbotMessages.pop)
            sleep 0.1
          end
          STDERR.puts "DEBUG: Got #{response.inspect}"
          amounts_dispensed.pop
        end
      end
    end
    
    render json: {"status" => "SUCCESS"}
  end

  def status
    # Leaving this unimplemented for now. I don't think that we actually need it currently?
    render json: {"status" => "SUCCESS"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beverage
      @beverage = Beverage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beverage_params
      params.require(:beverage).permit(:name, :identifier, :amount, :image_url, :image_data)
    end

    def motor_id_param
      params.require(:beverage).permit(:motor_id)["motor_id"]
    end
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/views/beverages/_form.html.erb
<%= form_with(model: beverage) do |form| %>
  <% if beverage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beverage.errors.count, "error") %> prohibited this beverage from being saved:</h2>

      <ul>
        <% beverage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :human_name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :identifier_code %>
    <%= form.text_field :identifier %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :image_data %>
    <%= form.text_field :image_data, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :associated_motor %>
    <%= form.collection_select :motor_id, Motor.order(:uuid), :id, :uuid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beverages/edit.html.erb
<h1>Editing Beverage</h1>

<%= render 'form', beverage: @beverage %>

<%= link_to 'Show', @beverage %> |
<%= link_to 'Back', beverages_path %>

app/views/beverages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beverages</h1>
<p><%= link_to "Goto Motors", motors_path %></p>

<table>
  <thead>
    <tr>
      <th>Human<br/>Name</th>
      <th>Identifier<br/>Code</th>
      <th>Amount</th>
      <th>Image url</th>
      <th>Image data</th>
      <th>Motor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beverages.each do |beverage| %>
      <tr>
        <td><%= beverage.name %></td>
        <td><%= beverage.identifier %></td>
        <td><%= beverage.amount %></td>
        <td><%= beverage.image_url %><br/><img src="<%= beverage.image_url %>" style="width:  200px" /></td>
        <td><%= beverage.image_data.to_s.empty? ? "" : "[BEVERAGE_DATA]" %></td>
        <td><%= beverage.motor&.uuid %></td>
        <td><%= link_to 'Show', beverage %></td>
        <td><%= link_to 'Edit', edit_beverage_path(beverage) %></td>
        <td><%= link_to 'Destroy', beverage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beverage', new_beverage_path %>

app/views/beverages/new.html.erb
<h1>New Beverage</h1>

<%= render 'form', beverage: @beverage %>

<%= link_to 'Back', beverages_path %>

app/views/beverages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Human Name:</strong>
  <%= @beverage.name %>
</p>

<p>
  <strong>Identifier Code:</strong>
  <%= @beverage.identifier %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @beverage.amount %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @beverage.image_url %>
</p>

<p>
  <img src="<%= @beverage.image_url %>" style="width: 400px" />
</p>

<p>
  <strong>Image data:</strong>
  <%= @beverage.image_data.to_s.empty? ? "" : "[BEVERAGE DATA]" %>
</p>

<p>
  <strong>Motor:</strong>
  <%= @beverage.motor&.uuid %>
</p>

<%= link_to 'Edit', edit_beverage_path(@beverage) %> |
<%= link_to 'Back', beverages_path %>