config/routes.rb
Rails.application.routes.draw do
  resources :beverages
  resources :motors
  get "/beverages/status/:id", to: "beverages#status"
  post "/beverages/dispense", to: "beverages#dispense"
  post "/motors/find", to: "motors#find"
  post "/motors/flush", to: "motors#flush"
end

app/models/motor.rb
class Motor < ApplicationRecord
  belongs_to :beverage, optional: true
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: %i[ show edit update destroy ]

  # GET /motors or /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1 or /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors or /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to @motor, notice: "Motor was successfully created." }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1 or /motors/1.json
  def update
    respond_to do |format|
      old_data = Motor.find(params[:id])
      STDERR.puts old_data.inspect
      STDERR.puts "-----"
      STDERR.puts motor_params.inspect
      STDERR.puts "-----"
      STDERR.puts @motor.inspect
      STDERR.puts "-----"

      if old_data && @motor.update(motor_params)
        STDERR.puts "sending to redis"
        Publisher.publish("drinkbot", {
          "name" => old_data.uuid,
          "command" =>"Name,#{motor_params["uuid"]}"}.to_json)
        STDERR.puts "====="
        format.html { redirect_to @motor, notice: "Motor was successfully updated." }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1 or /motors/1.json
  def destroy
    @motor.destroy
    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def find
    STDERR.puts "do find"
    motor_uuid = params["data"]["uuid"]
    STDERR.puts "motor_uuid: #{motor_uuid}"
    Publisher.publish("drinkbot", {
      "name" => motor_uuid,
      "command" =>"Find"}.to_json)
    ensure
    STDERR.puts ">>>>>"
    respond_to do |format|
      STDERR.puts "format: #{format.inspect}"
      format.html { STDERR.puts "html"; redirect_to motors_url, notice: "Find signal sent to the motor." }
      format.json { STDERR.puts "json"; head :no_content }
    end
  end

  # The request was to run the motors for n seconds, but the documentation
  # for the motors doesn't show a way to do that.
  # One can dispense a volume over time, a given volume, or at a given flow
  # rate. In addition, one case set a given volume that is dispensed every time
  # the motor comes on, but none of those are "pump for 10 seconds" or similar.
  # Do the flush command just pushes 30ml (about 1 ounce), for all motors.
  def flush
    flushed_list = []
    Motor.all.each do |motor|
      Publisher.publish("drinkbot", {
        "name" => motor.uuid,
        "command" => "D,30" # flush one ounce through the tubes
      })
      flushed_list << motor.uuid
    end
    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motors flushed: #{flushed_list.join(", ")}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motor_params
      params.require(:motor).permit(:uuid, :online)
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= form_with(model: motor) do |form| %>
  <% if motor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
        <% motor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid %>
  </div>

  <div class="field">
    <%= form.label :online %>
    <%= form.check_box :online %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/motors/edit.html.erb
<h1>Editing Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Show', @motor %> |
<%= link_to 'Back', motors_path %>

app/views/motors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motors</h1>
<p><%= link_to "Goto Beverages", beverages_path %></p>
<p></p><%= button_to "Flush Pumps", method: :post, action: "flush" %></p>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Online</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motors.each do |motor| %>
      <tr>
        <td><%= motor.uuid %></td>
        <td><%= motor.online %></td>
        <td><%= link_to 'Show', motor %></td>
        <td><%= link_to 'Edit', edit_motor_path(motor) %></td>
        <td><%= link_to 'Destroy', motor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to "Find", method: :post, action: "find", data: {uuid: motor.uuid} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motor', new_motor_path %>

app/views/motors/new.html.erb
<h1>New Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Back', motors_path %>

app/views/motors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @motor.uuid %>
</p>

<p>
  <strong>Online:</strong>
  <%= @motor.online %>
</p>

<%= link_to 'Edit', edit_motor_path(@motor) %> |
<%= link_to 'Back', motors_path %>